name: Nog Api Ci

on:
  push:
    branches: [ master ]
  release:
    types: [published]

jobs:
  test:
    name: publish tested image to docker hub
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - uses: whoan/docker-build-with-cache-action@v5
      with:
        image_name: gaugau3000/nog_api
        username: "${{ secrets.DOCKER_USERNAME }}"
        password: "${{ secrets.DOCKER_PASSWORD }}"
    - name : run tests
      run: docker-compose -f docker-compose.test.yml up --abort-on-container-exit --exit-code-from test
  deploy:
    needs: [test]
    name: deploy 
    runs-on: ubuntu-16.04
    steps:
      - name: deploy api to staging server
        if: github.ref == 'refs/heads/master'
        uses: appleboy/ssh-action@master
        env:
          APP_ENV: staging
          CONTENER_NAME: notonlygeek-api_staging
          NETWORK : notonlygeek_staging
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script_stop: "true"
          envs: CONTENER_NAME, GITHUB_REPOSITORY, NETWORK
          script: >
            cd /tmp &&
            curl -O https://raw.githubusercontent.com/gaugau3000/nog_api/master/scripts/ci/deploy_container.sh &&
            chmod +x ./deploy_container.sh &&
            CONTENER_NAME=${CONTENER_NAME} GITHUB_REPOSITORY=${GITHUB_REPOSITORY}
            NETWORK=${NETWORK} ./deploy_container.sh &&
            docker run --rm --network ${NETWORK} willwill/wait-for-it api:3000
            
        