name: Nog Api Ci

on:
  push:
    branches: [ master ]
  release:
    types: [published]

jobs:
  staging:
    if: github.ref == 'refs/heads/master'
    name: publish tested image to docker hub
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - uses: whoan/docker-build-with-cache-action@v5
      with:
        image_name: gaugau3000/nog_api
        username: gaugau3000
        password: "${{ secrets.DOCKER_PASSWORD }}"
    - name : run tests
      run: docker-compose -f docker-compose.test.yml up --abort-on-container-exit --exit-code-from test
    - name: Copy deploy scripts to remote
      uses: garygrossgarten/github-action-scp@release
      with:
        local: ./scripts/remote/
        remote: /tmp/nog_api/
        host: ${{ secrets.HOST }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        privateKey: ${{ secrets.DEPLOY_KEY }}
        port: ${{ secrets.DEPLOY_PORT }}
    - name: deploy api to staging server
      uses: appleboy/ssh-action@master
      env:
        APP_ENV: staging
        CONTENER_NAME: notonlygeek-api_staging
        NETWORK : notonlygeek_staging
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        key: ${{ secrets.DEPLOY_KEY }}
        port: ${{ secrets.DEPLOY_PORT }}
        script_stop: "true"
        envs: CONTENER_NAME, GITHUB_REPOSITORY, NETWORK
        script: >
          chmod +x /tmp/nog_api/deploy_container.sh &&
          CONTENER_NAME=${CONTENER_NAME} GITHUB_REPOSITORY=${GITHUB_REPOSITORY}
          NETWORK=${NETWORK} /tmp/nog_api/deploy_container.sh
            
        