name: Nog Api Ci

on:
  push:
    branches: [ master ]
  release:
    types: [published]

jobs:
  test:
    name: publish tested image to docker hub
    runs-on: ubuntu-16.04
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
    - uses: actions/checkout@v2
    - name: pull images for caching purpose
      run: scripts/ci/pull_from_cache.sh
    - name: build image stages 
      run: scripts/ci/build_images.sh
    - name : run tests
      run: docker-compose -f docker-compose.test.yml up --abort-on-container-exit --exit-code-from test
    - name: publish docker images to hub
      run: scripts/ci/publish_images.sh
  deploy:
    needs: [test]
    name: deploy 
    runs-on: ubuntu-16.04
    steps:
      - name: deploy api to staging server
        if: github.ref == 'refs/heads/master'
        uses: appleboy/ssh-action@master
        env:
          CONTENER_NAME: notonlygeek-api_staging
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script_stop: "true"
          envs: CONTENER_NAME, GITHUB_REPOSITORY, APP_ENV
          script: |
            cd /tmp
            curl -O https://raw.githubusercontent.com/gaugau3000/nog_api/master/scripts/ci/deploy_container.sh
            ./deploy_container.sh
            
        