name: Nog Api Ci


on:
  push:
    branches: [ master ]
  release:
    types: [published]


jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: create docker test network
      run: docker network create ci
    - name : run test smtp server
      run: docker run -d --name mail_nog --network ci mailhog/mailhog
    - name: build test image
      run: docker build -t nog_api:test -f Dockerfile.test .
    - name: run tests
      run: docker run --network ci nog_api:test